# -*- coding: utf-8 -*-
"""Cálculadora Básica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A8yeJOr84a-DweNYCN3J9R4kLytHEn9T

# Projeto Módulo 1

## Calculadora Básica
"""

#Função para verificar se  algo é uma Int ou não
def VerificaFloat(num):
  try:
    float(num)
    return True and float(num)
  except ValueError:
    return False
pass

#Função para solicitar os valores
def solicitarValores():

  global num1, num2 # tornando em variáveis globais
  print('Bem vindo a calculadora!')

  #Solicitando Primeiro Valor
  num1 = input('Digite o primeiro número: ') # valor 1

  #Verificando float do num1
  while VerificaFloat(num1) == False:
    print('Digite um valor válido!!')
    num1 = input('Digite o primeiro número: ') # valor 1
  else:
    num1 = float(num1)
  pass

  #Solicitando Segundo Valor
  num2 = input('Digite o segundo número: ') # valor 2

  #Verificando float do num2
  while VerificaFloat(num2) == False:
    print('Digite um valor válido!!')
    num2 = input('Digite o segundo número: ') # valor 2
  else:
    num2 = float(num2)
  pass

pass

## Função para definir a operação
def operacao(num1,num2):

  # Solitando ao usuário a operação desejada
  operacao = input('Escolha uma operação para começar:\n 1 -> soma \n 2 -> subtração \n 3 -> divisão \n 4 -> multiplicação\n' )

  # Verificando se o usuário digitou um valor válido
  while int(operacao) not in [1,2,3,4]:
    print('Digite um valor válido!!')
    operacao = input('Escolha uma operação para começar:\n 1 -> soma \n 2 -> subtração \n 3 -> divisão \n 4 -> multiplicação\n' )

  # Realizando a operação de acordo com a solicitação
  else:
    global total # tornando em variável globais
    match int(operacao):

        #Soma
        case 1:
          total = num1+num2
          print("Resultado: ", total)
          pass


        #Subtração
        case 2:
          total = num1-num2
          print("Resultado: ", total)
          pass

        #Divisão
        case 3:
          total = num1/num2
          print("Resultado: ", total)
          pass


        #Multiplicação
        case 4:
          total = num1*num2
          print("Resultado: ", total)
          pass
pass

#Função para continuar a conta
def continuarConta():

  # Caso o usuário ainda queira utilizar o número do resultado anterior
  continuar = input('Deseja continuar? S/N: ').upper()


  #Loop para continuar a conta sempre com o resultado anterior
  while continuar == 'S':

    #Solicita o próximo número
    num3 = input('Digite o próximo número: ')

    #Verifica Float do num3
    while VerificaFloat(num3) == False:
      print('Digite um valor válido!!')
      num3 = input('Digite o próximo número: ')
    else:
        num3 = float(num3)

    #volta a realizar as operações
    operacao(total,num3)


    continuar = input('Deseja continuar? S/N: ')

  else:
      #Finaliza a conta
      print("Acabamos por aqui, resultado final: ", total)

pass

solicitarValores()
operacao(num1,num2)
continuarConta()